spring:
  profiles:
    active: secret
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
app:
  cookie:
    secure: ${COOKIE_SECURE:false}
  external:
    url-template: https://schaledb.com/data/{{language}}/students.min.json
server:
  port: ${SERVER_PORT:8080}
